export type Language = 'en' | 'fr'

type UiTextMap = Record<Language, Record<string, string>>

export const uiText: UiTextMap = {
  en: {
    sections: 'SECTIONS',
    goAbout: 'Go to About',
    goProjects: 'Go to Projects',
    goExperience: 'Go to Education and Skills',
    about: 'About',
    projects: 'Projects',
    educationAndSkills: 'Education and Skills',
    status: 'STATUS: BACKEND_ENGINEERING_STUDENT',
    titleTop: 'BACKEND',
    titleBottom: 'ENGINEER',
    heroIntro:
      'Full-Stack Software Engineering student at 1337 with strong foundations in systems programming, networking, and backend development. Currently seeking a Full-Stack / Backend internship. I build scalable and secure applications with',
    statsProjects: 'PROJECTS',
    statsStack: 'TECH STACK',
    statsSchool: 'SCHOOL',
    terminalInit: 'initializing backend systems...',
    currentFocus: 'CURRENT_FOCUS',
    honingSkills: 'Honing More Skills',
    focusDescription:
      'Currently focused on building more systems using Django for authentication and data management, PostgreSQL, NestJS for WebSockets, Docker, and Redis.',
    selectedProjects: 'SELECTED_PROJECTS',
    hoverForDiagnostics: 'HOVER_OR_FOCUS_A_CARD_FOR_DIAGNOSTICS',
    aboutMeLabel: 'ABOUT_ME',
    aboutMeTitle: 'Critical thinker with a puzzle-driven mindset',
    aboutMeDescription:
      'I enjoy breaking complex problems into smaller logical steps, testing hypotheses fast, and iterating toward clean solutions. Puzzles and systems challenges are where I do my best work.',
    traitAnalysis: 'Critical Thinking',
    traitSolving: 'Problem Solving',
    traitPuzzles: 'Puzzle Enthusiast',
    fdfLabel: 'FDF_CANVAS',
    fdfTitle: 'Ambient FDF terrain study',
    fdfDescription: 'A lightweight canvas version of the wireframe logic, kept subtle and placed at the end of the page for now.',
    projectBrief: 'PROJECT_BRIEF',
    keyChallenges: 'KEY_CHALLENGES',
    myRole: 'MY_ROLE',
    tradeoff: 'TRADEOFF',
    proof: 'PROOF',
    githubSoon: 'GITHUB_REPO_LINK_COMING_SOON',
    tapForDetails: 'Tap a card for details',
    close: 'Close',
    educationSkills: 'EDUCATION_AND_SKILLS',
    foundation: 'Rigorous foundation + modern full-stack execution',
    education: 'Education',
    technicalSkills: 'Technical Skills',
    languages: 'Languages',
    languageDetails: 'Fluent in English and French. Native in Arabic.',
    email: 'Email',
    github: 'GitHub',
    linkedin: 'LinkedIn',
    openLinkedIn: 'Open LinkedIn',
  },
  fr: {
    sections: 'SECTIONS',
    goAbout: 'Aller a Profil',
    goProjects: 'Aller aux Projets',
    goExperience: 'Aller a Formation et Competences',
    about: 'Profil',
    projects: 'Projets',
    educationAndSkills: 'Formation et Competences',
    status: 'STATUT: ETUDIANT_INGENIERIE_BACKEND',
    titleTop: 'INGENIEUR',
    titleBottom: 'BACKEND',
    heroIntro:
      'Etudiant en ingenierie logicielle full-stack a 1337, avec des bases solides en programmation systeme, reseaux et backend. Actuellement a la recherche d un stage Full-Stack / Backend. Je construis des applications scalables et securisees avec',
    statsProjects: 'PROJETS',
    statsStack: 'TECH STACK',
    statsSchool: 'ECOLE',
    terminalInit: 'initialisation des systemes backend...',
    currentFocus: 'FOCUS_ACTUEL',
    honingSkills: 'Renforcer les competences',
    focusDescription:
      'Actuellement concentre sur la construction de systemes avec Django pour l authentification et la gestion de donnees, PostgreSQL, NestJS pour les WebSockets, Docker et Redis.',
    selectedProjects: 'PROJETS_SELECTIONNES',
    hoverForDiagnostics: 'SURVOLER_OU_FOCUS_UNE_CARTE_POUR_DIAGNOSTICS',
    aboutMeLabel: 'A_PROPOS',
    aboutMeTitle: 'Esprit analytique et passion des puzzles',
    aboutMeDescription:
      'J aime decomposer les problemes complexes en etapes logiques, tester rapidement des hypotheses, puis iterer vers des solutions propres. Les puzzles et les defis systemes sont mon terrain fort.',
    traitAnalysis: 'Esprit critique',
    traitSolving: 'Resolution de problemes',
    traitPuzzles: 'Passionne de puzzles',
    fdfLabel: 'CANEVAS_FDF',
    fdfTitle: 'Etude de terrain FDF ambiante',
    fdfDescription: 'Une version canvas legere de la logique wireframe, sobre et placee en fin de page pour le moment.',
    projectBrief: 'RESUME_PROJET',
    keyChallenges: 'DEFIS_CLES',
    myRole: 'MON_ROLE',
    tradeoff: 'COMPROMIS',
    proof: 'PREUVE',
    githubSoon: 'LIEN_GITHUB_BIENTOT_DISPONIBLE',
    tapForDetails: 'Touchez une carte pour les details',
    close: 'Fermer',
    educationSkills: 'FORMATION_ET_COMPETENCES',
    foundation: 'Base rigoureuse + execution full-stack moderne',
    education: 'Formation',
    technicalSkills: 'Competences Techniques',
    languages: 'Langues',
    languageDetails: 'Courant en anglais et francais. Arabe langue maternelle.',
    email: 'E-mail',
    github: 'GitHub',
    linkedin: 'LinkedIn',
    openLinkedIn: 'Ouvrir LinkedIn',
  },
}